[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
NEXT_PUBLIC_BTC_ADDRESS="0xD397b48D6FAf5311c166aEd21313f48e2A574525"
NEXT_PUBLIC_ETH_ADDRESS="0x122cCA6190b40De4fd3EE28A97c995D8C6524921"
NEXT_PUBLIC_FACTORY_ADDRESS="0xE3E00C0E1Aa234a81224bD9C6Ff13a625b45EF78"
NEXT_PUBLIC_FEECOLLECTOR_ADDRESS="0x935412D3A9570F8B479d6A2eC2E586A26bE0Ae9C"
NEXT_PUBLIC_FLASHSWAP_ADDRESS="0x461209c870760A1cF7C84aFEb2235F0C3e9e8EBA"
NEXT_PUBLIC_FSK_ADDRESS="0x784F97B0c8116727f8B6417b86975F77411e219B"
NEXT_PUBLIC_FUSDT_ADDRESS="0x02F1303F087C6D78f4142bC2dE8430348982D549"
NEXT_PUBLIC_HELPFUND_ADDRESS="0x8F6eC84595Ef52B2eB16BA6D1960e0110fC1c5C3"
NEXT_PUBLIC_LAUNCHPAD_FACTORY_ADDRESS="0xB1E2Ae6DB2bDFe7AC5599e79BDf997a9EBd2f581"
NEXT_PUBLIC_LOCKER_FACTORY_ADDRESS="0x949B162Cf291F42Bc04040357844E7BD2E5F07cC"
NEXT_PUBLIC_ROUTER_ADDRESS="0xF89671B5ac9DC671e941ace0171af22F9F0bfEFF"
NEXT_PUBLIC_SOL_ADDRESS="0x39C833e1f576d372E221E31cE82Dd52b520e970C"
NEXT_PUBLIC_STAKING_ADDRESS="0x746CA308a6d36E6634311fDCd45F2A0ED8C4E3AB"
NEXT_PUBLIC_USDC_ADDRESS="0x1C5206eEB5DF5127204495969955000D15D1C0bE"
NEXT_PUBLIC_WBNB_ADDRESS="0xae13d989dac2f0debff460ac112a837c89bBAa7cd"
